[package]
name = "raymarching"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
futures = "0.3.31"

[dependencies.sdl2]
version = "0.37.0"
features = ["ttf", "image"]
