name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2
      run: sudo apt-get install libsdl2-dev
    - name: Install SDL2-TTF
      run: sudo apt-get install libsdl2-ttf-dev
    - name: Install SDL2-Image
      run: sudo apt-get install libsdl2-image-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
